task: pose

model: DEIMv2Pose
criterion: Criterion
postprocessor: PostProcessor

use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 4    # save freq
grad_accum_steps: 2

DEIMv2Pose:
  backbone: DINOv3STAs
  encoder: HybridEncoder
  transformer: Transformer


Transformer:
  hidden_dim: 256
  dropout: 0.0
  nhead: 8
  num_queries: 60
  dim_feedforward: 1024
  num_decoder_layers: 6
  normalize_before: False
  return_intermediate_dec: True
  activation: 'relu'
  num_feature_levels: 3
  dec_n_points: 4
  learnable_tgt_init: True
  two_stage_type: 'standard'
  num_body_points: 17
  aux_loss: True
  num_classes: 2
  dec_pred_class_embed_share: False
  dec_pred_pose_embed_share: False
  two_stage_class_embed_share: False
  two_stage_bbox_embed_share: False
  cls_no_bias: False
  feat_strides: [8, 16, 32]
  eval_spatial_size: [640, 640]
  reg_max: 32
  reg_scale: 4

Criterion:
  num_classes: 2
  weight_dict: {loss_vfl: 2.0, loss_keypoints: 10.0, loss_oks: 4.0}
  focal_alpha: 0.25
  losses: ['vfl', 'keypoints']
  matcher:
    type: HungarianMatcher
    cost_class: 2.0
    cost_keypoints: 10.0
    cost_oks: 4.0
    focal_alpha: 0.25
  num_body_points: 17

PosePostProcessor:
  num_select: 60
  num_body_points: 17

train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomZoomOut, fill: 0, p: 0.5}
        - {type: RandomHorizontalFlip}
        - {type: ColorJitter}
        - {type: RandomHorizontalFlip}
        - {type: RandomResize, sizes: [640, 640], max_size: 1333}
        - {type: ToTensor}
        - {type: Normalize, mean: [0, 0, 0], std: [1, 1, 1]}
      policy:
        epoch: [5, 29, 48]   # list 
        ops: ['Mosaic', 'RandomCrop', 'RandomZoomOut']
      mosaic_prob: 0.5

  collate_fn:
    base_size: 640
    base_size_repeat: 4
    stop_epoch: 48

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomResize, sizes: [640, 640], max_size: 1333}
        - {type: ToTensor}
        - {type: Normalize, mean: [0, 0, 0], std: [1, 1, 1]}
  
  collate_fn:
    base_size: 640